#
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
#

Name:       harbour-muoto

# >> macros
%define __provides_exclude_from ^%{_datadir}/.*$
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:        Muoto
Version:        3.5.2
Release:        1
Group:          Qt/Qt
License:        GPLv3
Packager:       fravaccaro
URL:            https://github.com/uithemer/harbour-muoto
Source0:        %{name}-%{version}.tar.bz2

Requires:       sailfish-version >= 4.0.0
Obsoletes:      harbour-themepacksupport < 0.8.14
Provides:       harbour-themepacksupport = 0.8.14
Conflicts:      harbour-iconpacksupport
Conflicts:      clockwork
Conflicts:      harbour-dyncal
Conflicts:      harbour-dynclock
Obsoletes:      sailfishos-uithemer < 3.1.0
Provides:       sailfishos-uithemer = %{version}

BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(mlite5)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(sailfishsilica)
BuildRequires:  desktop-file-utils

%description
Enables customization of icons, fonts and pixel density in Sailfish OS.
Includes the former Theme pack support engine.
Icons are themed via the launcher daemon (desktop redirect and selective
hicolor inplace); fonts via fontconfig. Compatible with harbour-themepack-*
theme packages.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

# Upgrade from harbour-themepacksupport (2.2.1) / sailfishos-uithemer: run legacy
# restore scripts once while they still exist, then neutralise so the old
# package %preun does not invoke them again mid-transaction.
%pretrans -p /bin/sh
run_legacy_restore() {
    if [ -x "$1" ]; then
        "$1" || :
        printf '#!/bin/sh\nexit 0\n' > "$1" || :
    fi
}
for s in \
    /usr/share/harbour-themepacksupport/tps/sound-restore.sh \
    /usr/share/sailfishos-uithemer/sound-restore.sh
do
    run_legacy_restore "$s"
done
for s in \
    /usr/share/harbour-themepacksupport/tps/graphic-restore.sh
do
    run_legacy_restore "$s"
done
for s in \
    /usr/share/harbour-themepacksupport/tps/font-restore.sh
do
    run_legacy_restore "$s"
done
for s in \
    /usr/share/harbour-themepacksupport/icon-restore.sh \
    /usr/share/sailfishos-uithemer/icon-restore.sh
do
    run_legacy_restore "$s"
done
# Autoupdate hooks: neutralise only (not restore scripts).
if [ -d /usr/share/harbour-themepacksupport ]; then
    for s in disable-autoupdate.sh; do
        f="/usr/share/harbour-themepacksupport/$s"
        if [ -e "$f" ]; then
            printf '#!/bin/sh\nexit 0\n' > "$f" || :
        fi
    done
fi
# Fontconfig: rename before old %preun deletes 99-uithemer.conf.
fc_old=/home/defaultuser/.config/fontconfig/conf.d/99-uithemer.conf
fc_new=/home/defaultuser/.config/fontconfig/conf.d/99-muoto.conf
if [ -f "$fc_old" ]; then
    if [ ! -f "$fc_new" ]; then
        mv "$fc_old" "$fc_new" || :
    else
        rm -f "$fc_old" || :
    fi
    su defaultuser -c "fc-cache -f" 2>/dev/null || :
fi

%build
# >> build pre
# << build pre

%qtc_qmake5

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install
chmod 755 %{buildroot}%{_bindir}/harbour-muoto-update-icons 2>/dev/null || :
chmod 755 %{buildroot}%{_bindir}/harbour-muoto-oneshot-restore 2>/dev/null || :
chmod 755 %{buildroot}%{_bindir}/harbour-muoto-migrate-bulk-icons 2>/dev/null || :
chmod 755 %{buildroot}%{_bindir}/harbour-muoto-repair-folder-icons 2>/dev/null || :
chmod 755 %{buildroot}%{_datadir}/%{name}/service/muoto-dbus-wait.sh 2>/dev/null || :

mkdir -p %{buildroot}%{_datadir}/%{name}/launcher-icons

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
# 2.6.0: GUI loses the setuid bit. Privilege now comes via the
# dbus-activated /usr/libexec/harbour-muoto-helperd daemon
# (also packaged here, owned root:root, plain 0755 -- it elevates by
# being launched as root by dbus-daemon, not by the binary itself).
# 2.7.0: the headless harbour-muoto-icond binary is retired.
%attr(0755,root,root) %{_bindir}/%{name}
%attr(0755,root,root) %{_bindir}/harbour-muoto-update-icons
%attr(0755,root,root) %{_bindir}/harbour-muoto-oneshot-restore
%attr(0755,root,root) %{_bindir}/harbour-muoto-migrate-bulk-icons
%attr(0755,root,root) %{_bindir}/harbour-muoto-repair-folder-icons
%attr(0755,root,root) /usr/libexec/harbour-muoto-helperd
%attr(0755,root,root) /usr/libexec/harbour-muoto-install-listener
%attr(0755,root,root) /usr/libexec/harbour-muoto-launcher-icond
%{_libdir}/libmuoto-launcher.so*
/usr/include/muoto-launcher
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# Daemon plumbing: D-Bus name policy + activation file + interface
# introspection XMLs, plus the systemd unit (moved into place from
# /usr/share/harbour-muoto/service/ in %post). The polkit
# policy file shipped in 2.6.0-2.6.1 is gone in 2.6.2 -- auth is now
# enforced exclusively by the bus policy below.
%config /etc/dbus-1/system.d/org.muoto.Muoto1.conf
/usr/share/dbus-1/system-services/org.muoto.Muoto1.service
/usr/share/dbus-1/interfaces/org.muoto.Muoto1.Themes.xml
/usr/share/dbus-1/interfaces/org.muoto.Muoto1.Packs.xml
/usr/share/dbus-1/interfaces/org.muoto.Launcher1.Themes.xml
%config /etc/dbus-1/session.d/org.muoto.Launcher1.conf
/usr/lib/systemd/user/harbour-muoto-install-listener.service
/usr/lib/systemd/user/harbour-muoto-launcher-icond.service

# >> files
# << files

%post
mkdir -p %{_datadir}/%{name}/backup

# Replacing sailfishos-uithemer (Obsoletes): stop legacy helper before D-Bus handoff.
systemctl disable --now sailfishos-uithemer-helperd.service 2>/dev/null || :
systemctl stop sailfishos-uithemer-helperd.service 2>/dev/null || :

mv -f %{_datadir}/%{name}/service/harbour-muoto-helperd.service /etc/systemd/system/
mv -f %{_datadir}/%{name}/service/harbour-muoto-update-icons.service /etc/systemd/system/
mv -f %{_datadir}/%{name}/service/harbour-muoto-oneshot-restore.service /etc/systemd/system/
mv -f %{_datadir}/%{name}/service/harbour-muoto-repair-folder-icons.service /etc/systemd/system/
mkdir -p /etc/systemd/system/sailfish-upgrade-ui.service.d
cp -f %{_datadir}/%{name}/service/sailfish-upgrade-ui.service.d/muoto-oneshot-restore.conf \
    /etc/systemd/system/sailfish-upgrade-ui.service.d/muoto-oneshot-restore.conf
# 2.6.1: drop the old boot unit + binary name (reassert -> icond).
systemctl disable --now sailfishos-uithemer-reassert.service 2>/dev/null || :
rm -f /etc/systemd/system/sailfishos-uithemer-reassert.service
rm -f %{_bindir}/sailfishos-uithemer-reassert
# 2.7.0: retire the headless icond + the autoupdate/systemupgrade
# units. Stop + disable them on upgrade from <= 2.6.x; the matching
# unit files were removed from the package and the binary is gone.
systemctl disable --now themepacksupport-autoupdate.timer    2>/dev/null || :
systemctl disable --now themepacksupport-autoupdate.service  2>/dev/null || :
systemctl disable --now themepacksupport-systemupgrade.service 2>/dev/null || :
systemctl disable --now sailfishos-uithemer-icond.service    2>/dev/null || :
rm -f /etc/systemd/system/themepacksupport-autoupdate.timer
rm -f /etc/systemd/system/themepacksupport-autoupdate.service
rm -f /lib/systemd/system/themepacksupport-systemupgrade.service
rm -f /etc/systemd/system/sailfishos-uithemer-icond.service
rm -f %{_bindir}/sailfishos-uithemer-icond
rm -f /etc/systemd/system/sailfishos-uithemer-helperd.service
rm -f /etc/systemd/system/sailfishos-uithemer-rescan.path
rm -f /etc/systemd/system/sailfishos-uithemer-rescan.service
rm -f /etc/dbus-1/system.d/org.uithemer.UiThemer1.conf
rm -f /usr/share/dbus-1/system-services/org.uithemer.UiThemer1.service
rm -f /usr/share/dbus-1/interfaces/org.uithemer.UiThemer1.Themes.xml
rm -f /usr/share/dbus-1/interfaces/org.uithemer.UiThemer1.Packs.xml
# 2.6.0: pick up the new helper unit + dbus policy. 2.6.2: polkit
# reload dropped along with the policy file. Best-effort reloads
# (older systemd / community ports may not honour reload dbus).
systemctl daemon-reload
systemctl reload dbus            2>/dev/null || :
# 3.x: helperd is dbus-activated on demand (Restart=no); do not enable at boot.
systemctl disable harbour-muoto-helperd.service 2>/dev/null || :
systemctl stop harbour-muoto-helperd.service 2>/dev/null || :

systemctl enable harbour-muoto-update-icons.service 2>/dev/null || :
systemctl enable harbour-muoto-oneshot-restore.service 2>/dev/null || :

# A1: on upgrade only — reinstall graphics RPMs that own folder glyphs after the
# transaction (pkcon must not run inside %post; rpm db is locked). Marker gates retries.
if [ "$1" -ge 2 ]; then
    systemctl enable harbour-muoto-repair-folder-icons.service 2>/dev/null || :
    systemctl start --no-block harbour-muoto-repair-folder-icons.service 2>/dev/null || :
fi

# If a theme is already active, run boot apply once (no need to wait for reboot).
# Folder re-apply after a successful repair is also chained from the repair script.
pack=$(su defaultuser -c "dconf read /apps/harbour-muoto/activeIconPack" 2>/dev/null || true)
pack=${pack#\'}; pack=${pack%\'}
if [ -n "$pack" ] && [ "$pack" != "default" ]; then
    # Do not block RPM install on a full icon re-apply (can take minutes).
    systemctl start --no-block harbour-muoto-update-icons.service 2>/dev/null \
        || ( systemctl start harbour-muoto-update-icons.service >/dev/null 2>&1 & )
fi

MUOTO_UID=$(id -u defaultuser 2>/dev/null || echo "")
if [ -n "$MUOTO_UID" ]; then
    _wait=0
    while [ "$_wait" -lt 2 ] && [ ! -d "/run/user/$MUOTO_UID" ]; do
        sleep 2
        _wait=$((_wait + 1))
    done
    su defaultuser -c "mkdir -p ~/.config/systemd/user && ln -sf /usr/lib/systemd/user/harbour-muoto-install-listener.service ~/.config/systemd/user/; ln -sf /usr/lib/systemd/user/harbour-muoto-launcher-icond.service ~/.config/systemd/user/" 2>/dev/null || :
    if [ -d "/run/user/$MUOTO_UID" ]; then
        su defaultuser -c "XDG_RUNTIME_DIR=/run/user/$MUOTO_UID systemctl --user daemon-reload" 2>/dev/null || :
        su defaultuser -c "XDG_RUNTIME_DIR=/run/user/$MUOTO_UID systemctl --user enable --now harbour-muoto-install-listener.service" 2>/dev/null || :
        su defaultuser -c "XDG_RUNTIME_DIR=/run/user/$MUOTO_UID systemctl --user try-restart harbour-muoto-install-listener.service" 2>/dev/null || :
        su defaultuser -c "XDG_RUNTIME_DIR=/run/user/$MUOTO_UID systemctl --user enable --now harbour-muoto-launcher-icond.service" 2>/dev/null || :
    else
        su defaultuser -c "mkdir -p ~/.config/systemd/user && ln -sf /usr/lib/systemd/user/harbour-muoto-launcher-icond.service ~/.config/systemd/user/" 2>/dev/null || :
        su defaultuser -c "systemctl --user daemon-reload" 2>/dev/null || :
        su defaultuser -c "systemctl --user enable harbour-muoto-install-listener.service" 2>/dev/null || :
        su defaultuser -c "systemctl --user enable harbour-muoto-launcher-icond.service" 2>/dev/null || :
    fi
fi
setcap cap_dac_override+ep /usr/libexec/harbour-muoto-launcher-icond 2>/dev/null || :
mkdir -p %{_datadir}/%{name}/launcher-icons 2>/dev/null || :

# 3.2: one-shot bulk stock restore from 3.1 backup/icons, then retire tree.
/usr/bin/harbour-muoto-migrate-bulk-icons 2>/dev/null || :
# Drop folder backups before wiping backup/icons: may be nested (bug) or poisoned
# after a prior wipe + re-apply. Repair oneshot restores live stock via pkcon.
rm -rf %{_datadir}/%{name}/backup/icons/folder-icons \
       %{_datadir}/%{name}/backup/folder-icons 2>/dev/null || :
rm -rf %{_datadir}/%{name}/backup/icons 2>/dev/null || :

su defaultuser -c "dconf reset /apps/harbour-muoto/launcherInstantApply" 2>/dev/null || :

MUOTO_UID=$(id -u defaultuser 2>/dev/null || echo "")
if [ -n "$MUOTO_UID" ] && [ -d "/run/user/$MUOTO_UID" ]; then
    _pack=$(su defaultuser -c "dconf read /apps/harbour-muoto/activeIconPack" 2>/dev/null || true)
    _pack=${_pack#\'}; _pack=${_pack%\'}
    if [ -n "$_pack" ] && [ "$_pack" != "default" ]; then
        su defaultuser -c "XDG_RUNTIME_DIR=/run/user/$MUOTO_UID systemctl --user try-restart harbour-muoto-launcher-icond.service" 2>/dev/null || :
    fi
fi

# Icon ops flock sentinel (GUI probe + launcher-icond).
mkdir -p %{_datadir}/%{name}/tmp 2>/dev/null || :
touch %{_datadir}/%{name}/icon-ops.lock 2>/dev/null || :
chmod 0666 %{_datadir}/%{name}/icon-ops.lock 2>/dev/null || :

# 2.4.5: the vendor dconf defaults file is no longer shipped. If it was
# installed by an older version (<= 2.4.4), drop it and refresh the dconf db.
if [ -f /etc/dconf/db/vendor.d/sailfishos-uithemer.txt ]; then
    rm -f /etc/dconf/db/vendor.d/sailfishos-uithemer.txt
    dconf update || :
fi

# 2.6.0: the themepacksupport CLI symlink and the harbour-themepacksupport
# backup/config.cfg migration are gone. The new daemon owns the same ops
# over D-Bus and the legacy backup/ tree (PNG-replacement era) is no longer
# read by anything we ship.

# 2.3.x left an icon-current pointer file behind; it is no longer used.
rm -f %{_datadir}/%{name}/icon-current
# 2.4.1 and earlier kept a graphic-current state file for the (now removed)
# graphic theming. Drop it on upgrade so it does not linger.
rm -f %{_datadir}/%{name}/graphic-current
# 2.4.3 and earlier kept a sound-current state file and a backup/sound
# directory for the (now removed) sound theming. %pretrans already restored
# the user's sounds; drop the leftovers so they do not linger.
rm -f %{_datadir}/%{name}/sound-current
rm -rf %{_datadir}/%{name}/backup/sound
# 2.4.5 and earlier kept a /usr/share/harbour-muoto/tmp/iconspreview.png
# for the pack / cover preview. The preview is now served from memory
# via a QQuickImageProvider; drop the leftover file and the (now unused) dir.
rm -f %{_datadir}/%{name}/tmp/iconspreview.png
rmdir --ignore-fail-on-non-empty %{_datadir}/%{name}/tmp 2>/dev/null || :
# 2.4.x and earlier kept a font-current pointer + backup/font* trees from
# the bash-based font theming. 2.5.0 switched to fontconfig aliasing under
# ~/.config/fontconfig/conf.d, so neither is used anymore. Drop them.
rm -f %{_datadir}/%{name}/font-current
rm -rf %{_datadir}/%{name}/backup/font
rm -rf %{_datadir}/%{name}/backup/font-droid
rm -rf %{_datadir}/%{name}/backup/font-nonlatin

# 2.5.4: density customizations are now always enabled. Mirror
# DensityEnabler::ensureEnabled() at install time so the vendor dconf locks
# for silica-configs.txt / ui-configs.txt are moved out of the way.
# Idempotent: always move src when present (SFOS may restore locks while .bk exists).
mkdir -p %{_datadir}/%{name}/backup/dlocks
for f in silica-configs.txt ui-configs.txt; do
    src=/etc/dconf/db/vendor.d/locks/$f
    bk=%{_datadir}/%{name}/backup/dlocks/$f.bk
    if [ -f "$src" ]; then
        mv -f "$src" "$bk"
    fi
done
dconf update || :
# 2.5.4: tps/enable-dpi.sh used to drop the captured icon_size_launcher
# into a plain file at $main/icon-z. The C++ port (2.5.4-2.5.5) stored it
# in dconf as iconSizeLauncherSeed; 2.5.6 retired the seed entirely (restore
# now resets icon_size_launcher to vendor default). Drop both leftovers.
rm -f %{_datadir}/%{name}/icon-z
su defaultuser -c "dconf reset /desktop/lipstick/sailfishos-uithemer/iconSizeLauncherSeed" 2>/dev/null || :

%preun
if [ $1 -eq 0 ]; then
    # Quiesce automation before restore (avoid ApplyIcons vs RestoreIcons on icon-ops.lock).
    systemctl stop harbour-muoto-update-icons.service 2>/dev/null || true
    MUOTO_UID=$(id -u defaultuser 2>/dev/null || echo "")
    if [ -n "$MUOTO_UID" ]; then
        su defaultuser -c "XDG_RUNTIME_DIR=/run/user/$MUOTO_UID systemctl --user disable --now harbour-muoto-launcher-icond.service" 2>/dev/null || true
        su defaultuser -c "XDG_RUNTIME_DIR=/run/user/$MUOTO_UID systemctl --user disable --now harbour-muoto-install-listener.service" 2>/dev/null || true
    fi
    if [ -n "$MUOTO_UID" ] && [ -d "/run/user/$MUOTO_UID" ]; then
        su defaultuser -c "XDG_RUNTIME_DIR=/run/user/$MUOTO_UID /usr/libexec/harbour-muoto-launcher-icond --restore-once" 2>/dev/null || true
    else
        /usr/libexec/harbour-muoto-launcher-icond --restore-once 2>/dev/null || true
    fi
    /usr/bin/harbour-muoto-migrate-bulk-icons 2>/dev/null || true
    # Full stock restore while helperd + backup still on disk; non-zero aborts removal.
    /usr/bin/harbour-muoto-oneshot-restore --uninstall

    rm -rf /home/defaultuser/.local/share/%{name}
    rm -rf /home/defaultuser/.cache/%{name}

    # Legacy unit name (<= 2.6.0); harmless no-op on fresh installs.
    systemctl disable sailfishos-uithemer-reassert.service 2>/dev/null || :
    rm -f /etc/systemd/system/sailfishos-uithemer-reassert.service
    # 2.6.0: stop the privileged helper before files vanish so it does
    # not race the rest of %preun on a dbus-activated re-spawn.
    systemctl stop harbour-muoto-helperd.service 2>/dev/null || :
    # 2.7.1: stop the rescan path unit too -- otherwise the in-flight
    # %preun would tick it (we remove files under
    # /home/defaultuser/.local/share/sailfishos-uithemer below) and
    # systemd would retry a service whose binary is about to vanish.
    systemctl disable --now harbour-muoto-rescan.path 2>/dev/null || :
    systemctl disable --now harbour-muoto-update-icons.service 2>/dev/null || :
    systemctl disable --now harbour-muoto-oneshot-restore.service 2>/dev/null || :
    systemctl disable --now harbour-muoto-repair-folder-icons.service 2>/dev/null || :
    rm -f /etc/systemd/system/sailfish-upgrade-ui.service.d/muoto-oneshot-restore.conf
    rmdir /etc/systemd/system/sailfish-upgrade-ui.service.d 2>/dev/null || :
fi

%postun
if [ $1 -eq 0 ]; then
    rm -f /etc/systemd/system/sailfishos-uithemer-reassert.service
    rm -f /etc/systemd/system/harbour-muoto-helperd.service
    # 2.7.1: drop the rescan path+service we placed in %post. Files
    # under %{_datadir}/%{name} are removed by RPM automatically.
    rm -f /etc/systemd/system/harbour-muoto-rescan.path
    rm -f /etc/systemd/system/harbour-muoto-rescan.service
    rm -f /etc/systemd/system/harbour-muoto-update-icons.service
    rm -f /etc/systemd/system/harbour-muoto-oneshot-restore.service
    rm -f /etc/systemd/system/harbour-muoto-repair-folder-icons.service
    rm -f /etc/systemd/system/sailfish-upgrade-ui.service.d/muoto-oneshot-restore.conf
    rm -f %{_datadir}/%{name}/folder-icons-rpm-healed
    systemctl daemon-reload
    # 2.6.0: refresh dbus so the just-removed system bus name drops
    # from the registry. 2.6.2: polkit reload dropped.
    systemctl reload dbus    2>/dev/null || :
fi

%transfiletriggerin -- %{_datadir}
if grep -qF %{_datadir}/harbour-themepack- ; then
    MUOTO_UID=$(id -u defaultuser 2>/dev/null || echo "")
    if [ -n "$MUOTO_UID" ] && [ -d "/run/user/$MUOTO_UID" ]; then
        su defaultuser -c "XDG_RUNTIME_DIR=/run/user/$MUOTO_UID systemctl --user try-restart harbour-muoto-launcher-icond.service" 2>/dev/null || :
    fi
fi
