#
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
#

Name:       sailfishos-uithemer

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:        UI Themer
Version:        2.7.0
Release:        1
Group:          Qt/Qt
License:        GPLv3
Packager:       fravaccaro <fravaccaro@jollacommunity.it>
URL:            https://github.com/uithemer/sailfishos-uithemer
Source0:        %{name}-%{version}.tar.bz2
Source100:      sailfishos-uithemer.yaml

Requires:       sailfish-version >= 2.1.4
Obsoletes:      harbour-themepacksupport < 0.8.14
Provides:       harbour-themepacksupport = 0.8.14
Conflicts:      harbour-iconpacksupport

BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  desktop-file-utils

%description
Enables customization of icons, fonts and pixel density in Sailfish OS.
Includes the former Theme pack support engine and CLI (themepacksupport).
Icons are applied by rewriting the Icon= entries in .desktop files (no PNG
replacement). Original Icon= values are tracked in a JSON manifest so the
default theme can always be restored.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

# Before harbour-themepacksupport is erased on upgrade, neutralise its %preun
# restore scripts so the user's theme is not reset mid-transaction.
%pretrans -p /bin/sh
if [ -d /usr/share/harbour-themepacksupport ]; then
    for s in icon-restore.sh disable-autoupdate.sh; do
        f="/usr/share/harbour-themepacksupport/$s"
        if [ -e "$f" ]; then
            printf '#!/bin/sh\nexit 0\n' > "$f" || :
        fi
    done
fi
# Same for the previous sailfishos-uithemer (<= 2.3.x) which still shipped icon-restore.sh.
old=/usr/share/sailfishos-uithemer/icon-restore.sh
if [ -e "$old" ]; then
    printf '#!/bin/sh\nexit 0\n' > "$old" || :
fi

# 2.4.4: sound theming is being removed. If the previous package still has
# sound-restore.sh on disk (i.e. we are upgrading from <= 2.4.3 with a sound
# theme possibly applied), run it once now to revert
# /usr/share/sounds/jolla-ambient/stereo to the user's saved originals
# BEFORE the new package overlays the script set and removes sound-restore.sh.
# The %post hook then deletes sound-current and backup/sound. Safe on fresh
# installs (the script is absent and the test fails).
sr=/usr/share/sailfishos-uithemer/sound-restore.sh
if [ -x "$sr" ]; then
    "$sr" || :
fi

%build
# >> build pre
# << build pre

%qtc_qmake5

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
# 2.6.0: GUI loses the setuid bit. Privilege now comes via the
# dbus-activated /usr/libexec/sailfishos-uithemer-helperd daemon
# (also packaged here, owned root:root, plain 0755 -- it elevates by
# being launched as root by dbus-daemon, not by the binary itself).
# 2.7.0: the headless sailfishos-uithemer-icond binary is retired
# (the auto-theming watcher in helperd covers the same ground).
%attr(0755,root,root) %{_bindir}/%{name}
%attr(0755,root,root) /usr/libexec/sailfishos-uithemer-helperd
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# Daemon plumbing: D-Bus name policy + activation file + interface
# introspection XMLs, plus the systemd unit (moved into place from
# /usr/share/sailfishos-uithemer/service/ in %post). The polkit
# policy file shipped in 2.6.0-2.6.1 is gone in 2.6.2 -- auth is now
# enforced exclusively by the bus policy below.
%config /etc/dbus-1/system.d/org.uithemer.UiThemer1.conf
/usr/share/dbus-1/system-services/org.uithemer.UiThemer1.service
/usr/share/dbus-1/interfaces/org.uithemer.UiThemer1.Themes.xml
/usr/share/dbus-1/interfaces/org.uithemer.UiThemer1.Packs.xml

# >> files
# << files

%post
# 2.6.0: only the service helpers under service/ are shell scripts now;
# the legacy tps/ + scripts/ shell suite is gone (every privileged op
# lives in the daemon). Keep the +x for the systemd ExecStart helpers.
chmod +x %{_datadir}/%{name}/service/*.sh
mkdir -p %{_datadir}/%{name}/backup

mv -f %{_datadir}/%{name}/service/sailfishos-uithemer-helperd.service /etc/systemd/system/
# 2.7.1: rescan path+service for background auto-theming. The .path
# unit watches /usr/share/applications and
# /home/defaultuser/.local/share/applications and triggers the .service,
# which runs as defaultuser, reads iconOverlay from dconf, and asks
# helperd over the system bus to run a unified rescan. This is what
# themes APK icons after apkd-bridge installs/updates an app while the
# GUI is closed.
mv -f %{_datadir}/%{name}/service/sailfishos-uithemer-rescan.path /etc/systemd/system/
mv -f %{_datadir}/%{name}/service/sailfishos-uithemer-rescan.service /etc/systemd/system/
# rescan.sh stays under %{_datadir}/%{name}/service/ -- the chmod +x
# at the top of %post (chmod +x .../service/*.sh) already armed it.
# 2.6.1: drop the old boot unit + binary name (reassert -> icond).
systemctl disable --now sailfishos-uithemer-reassert.service 2>/dev/null || :
rm -f /etc/systemd/system/sailfishos-uithemer-reassert.service
rm -f %{_bindir}/sailfishos-uithemer-reassert
# 2.7.0: retire the headless icond + the autoupdate/systemupgrade
# units. Stop + disable them on upgrade from <= 2.6.x; the matching
# unit files were removed from the package and the binary is gone.
systemctl disable --now themepacksupport-autoupdate.timer    2>/dev/null || :
systemctl disable --now themepacksupport-autoupdate.service  2>/dev/null || :
systemctl disable --now themepacksupport-systemupgrade.service 2>/dev/null || :
systemctl disable --now sailfishos-uithemer-icond.service    2>/dev/null || :
rm -f /etc/systemd/system/themepacksupport-autoupdate.timer
rm -f /etc/systemd/system/themepacksupport-autoupdate.service
rm -f /lib/systemd/system/themepacksupport-systemupgrade.service
rm -f /etc/systemd/system/sailfishos-uithemer-icond.service
rm -f %{_bindir}/sailfishos-uithemer-icond
# 2.6.0: pick up the new helper unit + dbus policy. 2.6.2: polkit
# reload dropped along with the policy file. Best-effort reloads
# (older systemd / community ports may not honour reload dbus).
systemctl daemon-reload
systemctl reload dbus            2>/dev/null || :
# 2.6.2: the helperd is now always-on (Before=systemd-user-sessions
# and Restart=always). Enable + start it so
# the GUI's first call after install does not race bus-activation.
systemctl enable --now sailfishos-uithemer-helperd.service 2>/dev/null || :
# 2.7.1: enable the rescan .path so apkd-bridge installs trigger an
# auto-theming pass even when the GUI is closed. Failure is non-fatal
# on community ports that lack systemd path units.
systemctl enable --now sailfishos-uithemer-rescan.path 2>/dev/null || :

# Obsolete drop-in from 2.3.0 and earlier (removed in 2.3.1)
rm -f /etc/systemd/system/aliendalvik.service.d/10-themepacksupport.conf

# Seed an empty icon backup manifest if one does not exist yet.
if [ ! -e %{_datadir}/%{name}/icon-backup.json ]; then
    printf '{"version":1,"active_icon_pack":null,"entries":{}}\n' > %{_datadir}/%{name}/icon-backup.json
fi

# 2.4.5: the vendor dconf defaults file is no longer shipped. If it was
# installed by an older version (<= 2.4.4), drop it and refresh the dconf db.
if [ -f /etc/dconf/db/vendor.d/sailfishos-uithemer.txt ]; then
    rm -f /etc/dconf/db/vendor.d/sailfishos-uithemer.txt
    dconf update || :
fi

# 2.6.0: the themepacksupport CLI symlink and the harbour-themepacksupport
# backup/config.cfg migration are gone. The new daemon owns the same ops
# over D-Bus and the legacy backup/ tree (PNG-replacement era) is no longer
# read by anything we ship.

# 2.3.x left an icon-current pointer file behind; it is no longer used.
rm -f %{_datadir}/%{name}/icon-current
# 2.4.1 and earlier kept a graphic-current state file for the (now removed)
# graphic theming. Drop it on upgrade so it does not linger.
rm -f %{_datadir}/%{name}/graphic-current
# 2.4.3 and earlier kept a sound-current state file and a backup/sound
# directory for the (now removed) sound theming. %pretrans already restored
# the user's sounds; drop the leftovers so they do not linger.
rm -f %{_datadir}/%{name}/sound-current
rm -rf %{_datadir}/%{name}/backup/sound
# 2.4.5 and earlier kept a /usr/share/sailfishos-uithemer/tmp/iconspreview.png
# for the ConfirmPage / cover preview. The preview is now served from memory
# via a QQuickImageProvider; drop the leftover file and the (now unused) dir.
rm -f %{_datadir}/%{name}/tmp/iconspreview.png
rmdir --ignore-fail-on-non-empty %{_datadir}/%{name}/tmp 2>/dev/null || :
# 2.4.x and earlier kept a font-current pointer + backup/font* trees from
# the bash-based font theming. 2.5.0 switched to fontconfig aliasing under
# ~/.config/fontconfig/conf.d, so neither is used anymore. Drop them.
rm -f %{_datadir}/%{name}/font-current
rm -rf %{_datadir}/%{name}/backup/font
rm -rf %{_datadir}/%{name}/backup/font-droid
rm -rf %{_datadir}/%{name}/backup/font-nonlatin

# 2.5.4: density customizations are now always enabled. Mirror
# DensityEnabler::ensureEnabled() at install time so the vendor dconf locks
# for silica-configs.txt / ui-configs.txt are moved out of the way.
# Idempotent: per-file move is skipped when the .bk already exists.
mkdir -p %{_datadir}/%{name}/backup/dlocks
for f in silica-configs.txt ui-configs.txt; do
    src=/etc/dconf/db/vendor.d/locks/$f
    bk=%{_datadir}/%{name}/backup/dlocks/$f.bk
    if [ -f "$src" ] && [ ! -f "$bk" ]; then
        mv "$src" "$bk" || :
    fi
done
dconf update || :
# 2.5.4: tps/enable-dpi.sh used to drop the captured icon_size_launcher
# into a plain file at $main/icon-z. The C++ port (2.5.4-2.5.5) stored it
# in dconf as iconSizeLauncherSeed; 2.5.6 retired the seed entirely (restore
# now resets icon_size_launcher to vendor default). Drop both leftovers.
rm -f %{_datadir}/%{name}/icon-z
su - defaultuser -c "dconf reset /desktop/lipstick/sailfishos-uithemer/iconSizeLauncherSeed" 2>/dev/null || :

%preun
if [ $1 -eq 0 ]; then
    rm -rf /home/defaultuser/.local/share/%{name}
    rm -rf /home/defaultuser/.cache/%{name}

    # Legacy unit name (<= 2.6.0); harmless no-op on fresh installs.
    systemctl disable sailfishos-uithemer-reassert.service 2>/dev/null || :
    rm -f /etc/systemd/system/sailfishos-uithemer-reassert.service
    # 2.6.0: stop the privileged helper before files vanish so it does
    # not race the rest of %preun on a dbus-activated re-spawn.
    systemctl stop sailfishos-uithemer-helperd.service 2>/dev/null || :
    # 2.7.1: stop the rescan path unit too -- otherwise the in-flight
    # %preun would tick it (we remove files under
    # /home/defaultuser/.local/share/sailfishos-uithemer below) and
    # systemd would retry a service whose binary is about to vanish.
    systemctl disable --now sailfishos-uithemer-rescan.path 2>/dev/null || :
    # 2.7.0: OptionsPage retirement dropped the headless icond binary
    # plus the autoupdate/systemupgrade units; the on-uninstall
    # auto-restore of themed .desktop files went with them. Users
    # should run "Restore theme" from the app before uninstalling.

    # 2.5.0 font theming is just a per-user fontconfig conf file; revert by
    # removing it and refreshing the cache as defaultuser. No-op if absent.
    f=/home/defaultuser/.config/fontconfig/conf.d/99-uithemer.conf
    if [ -f "$f" ]; then
        rm -f "$f"
        su - defaultuser -c "fc-cache -f" || true
    fi

    # 2.5.6: scripts/restore_dpi.sh + tps/restore_dpr.sh + tps/restore_iz.sh
    # were retired in favour of two inline dconf resets so uninstall still
    # brings DPR + icon_size_launcher back to the vendor default.
    su - defaultuser -c "dconf reset /desktop/sailfish/silica/theme_pixel_ratio" || true
    su - defaultuser -c "dconf reset /desktop/sailfish/silica/icon_size_launcher" || true

    # 2.5.4: enable-dpi.sh / disable-dpi.sh were dropped; the equivalent
    # uninstall step (restore vendor dconf locks moved by %post) now runs
    # inline. No-op when the .bk files are absent.
    for f in silica-configs.txt ui-configs.txt; do
        bk=%{_datadir}/%{name}/backup/dlocks/$f.bk
        dst=/etc/dconf/db/vendor.d/locks/$f
        if [ -f "$bk" ]; then
            mv "$bk" "$dst" || :
        fi
    done
    dconf update || :
fi

%postun
if [ $1 -eq 0 ]; then
    rm -f /etc/systemd/system/sailfishos-uithemer-reassert.service
    rm -f /etc/systemd/system/sailfishos-uithemer-helperd.service
    # 2.7.1: drop the rescan path+service we placed in %post. Files
    # under %{_datadir}/%{name} are removed by RPM automatically.
    rm -f /etc/systemd/system/sailfishos-uithemer-rescan.path
    rm -f /etc/systemd/system/sailfishos-uithemer-rescan.service
    systemctl daemon-reload
    # 2.6.0: refresh dbus so the just-removed system bus name drops
    # from the registry. 2.6.2: polkit reload dropped.
    systemctl reload dbus    2>/dev/null || :
fi
