#ifndef MUOTOLAUNCHERGLOBAL_H
#define MUOTOLAUNCHERGLOBAL_H

#include <QtGlobal>

#ifdef MUOTO_LAUNCHER_BUILD_LIBRARY
#define MUOTO_LAUNCHER_EXPORT Q_DECL_EXPORT
#else
#define MUOTO_LAUNCHER_EXPORT Q_DECL_IMPORT
#endif

#endif // MUOTOLAUNCHERGLOBAL_H
